version: "3.8"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: safeenoughaswell
      MYSQL_DATABASE: forum
      MYSQL_USER: forum
      MYSQL_PASSWORD: chingchongbingbong
